### login
POST http://127.0.0.1:8080/chatgpt/login
Content-Type: application/json

{
  "username": "{{username}}",
  "password": "{{password}}"
}

### get conversations
GET http://127.0.0.1:8080/chatgpt/conversations
Authorization: Bearer {{accessToken}}

### create conversation
POST http://127.0.0.1:8080/chatgpt/conversation
Authorization: Bearer {{accessToken}}
Content-Type: application/json
Accept: text/event-stream

{
  "action": "next",
  "messages": [
    {
      "id": "{{$random.uuid}}",
      "author": {
        "role": "user"
      },
      "content": {
        "content_type": "text",
        "parts": [
          "who are you?"
        ]
      },
      "metadata": {}
    }
  ],
  "model": "text-davinci-002-render-sha",
  "timezone_offset_min": -480,
  "history_and_training_disabled": false,
  "arkose_token": null
}

> {%
    response.body.onEachLine((data) => {
        client.log(data.toString());
    })
%}
