### login
POST {{baseUrl}}/platform/login
Content-Type: application/json

{
  "username": "{{username}}",
  "password": "{{password}}"
}

### get models
GET {{baseUrl}}/platform/v1/models
Authorization: Bearer {{apiKey}}

### get model
GET {{baseUrl}}/platform/v1/models/gpt-3.5-turbo-16k-0613
Authorization: Bearer {{apiKey}}

### Create chat completion
POST {{baseUrl}}/platform/v1/chat/completions
Content-Type: application/json
Authorization: Bearer {{apiKey}}

{
  "model": "gpt-3.5-turbo",
  "messages": [
    {
      "role": "system",
      "content": "You are a helpful assistant."
    },
    {
      "role": "user",
      "content": "Hello!"
    }
  ],
  "stream": true
}

### Create completion
POST {{baseUrl}}/platform/v1/completions
Content-Type: application/json
Authorization: Bearer {{apiKey}}

{
  "model": "text-davinci-003",
  "prompt": "Say this is a test",
  "max_tokens": 7,
  "temperature": 0,
  "stream": true
}

### get user api_keys
GET {{baseUrl}}/platform/dashboard/user/api_keys
Authorization: Bearer {{apiKey}}

### get billing credit_grants
GET {{baseUrl}}/platform/dashboard/billing/credit_grants
Authorization: Bearer {{apiKey}}

### get billing subscription
GET {{baseUrl}}/platform/dashboard/billing/subscription
Authorization: Bearer {{apiKey}}

### get billing usage
GET {{baseUrl}}/platform/dashboard/billing/usage?end_date=2023-07-01&start_date=2023-06-01
Authorization: Bearer {{apiKey}}
